import bcrypt from "bcryptjs";
import { Role, Status } from "../../generated/prisma/client.js";
import { prisma } from "../../config/database.js";
import { userPublicFields } from "../users/user.types.js";
import { TokenService } from "./token.service.js";
import type { RegisterInput } from "./auth.validation.js";
import type { ApiError } from "../../shared/types/common.types.js";

export class AuthService {
  constructor(private readonly tokenService = new TokenService()) {}

  public async registerUser(input: RegisterInput) {
    // Check mobile uniqueness
    const existingMobile = await prisma.user.findUnique({
      where: { mobile: input.mobile },
      select: { id: true },
    });

    if (existingMobile) {
      const error = new Error("Mobile number already registered") as ApiError;
      error.status = 409;
      throw error;
    }

    // Check email uniqueness (only when provided)
    if (input.email) {
      const existingEmail = await prisma.user.findUnique({
        where: { email: input.email },
        select: { id: true },
      });

      if (existingEmail) {
        const error = new Error("Email already registered") as ApiError;
        error.status = 409;
        throw error;
      }
    }

    // Hash password with salt rounds = 12
    const hashedPassword = await bcrypt.hash(input.password, 12);

    // Create user + optional StudentProfile in a single transaction
    const user = await prisma.$transaction(async (tx) => {
      const created = await tx.user.create({
        data: {
          fullName: input.fullName,
          mobile: input.mobile,
          email: input.email ?? null,
          password: hashedPassword,
          role: input.role === "OPERATION" ? Role.OPERATION : Role.STUDENT,
          status: Status.ACTIVE,
          // tenantId is auto-generated by Prisma (@default(uuid()))
        },
        select: userPublicFields,
      });

      if (input.role === "STUDENT") {
        await tx.studentProfile.create({
          data: { userId: created.id },
        });
      }

      return created;
    });

    // Generate JWT: payload = { userId, role, tenantId }, expiry from env (fallback 30d)
    const accessToken = this.tokenService.generateRegisterToken(
      user.id,
      user.role,
      user.tenantId,
    );

    // Return user WITHOUT password + accessToken
    return { user, accessToken };
  }
}
